### ISSUE TITLE
Use a uniform accent color scheme for the website

### ISSUE THREAD

**Issue by biswabaibhab007** [Debasishb77/IBM_Frontend#47]
- #023460 as the accent color for all the coloured text other than black ones
- for buttons use a darker shade and for hover use a lighter shade

**Comment by biswabaibhab007** [comment]
@Subhodeep19 :  impacts page
@Nikhar17 and @Subodha123456 : doctors page

**Comment by SoulNikhar** [comment]
@Debasishb77  assign this to @Subodha123456

**Comment by biswabaibhab007** [comment]
solved
